version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SERVER_PORT=9090
      - DATASOURCE_URL=jdbc:postgresql://db:5432/explore-with-me
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test


  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-database
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore-with-me
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test